[package]
name = "mpvcast"
version = "0.1.0"
edition = "2021"

[dependencies]
libmpv = { path = "./libmpv-rs" }
prost = "0.13"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[build-dependencies]
prost-build = "0.13.5"
