[package]
name = "mpvcast"
version = "0.1.0"
edition = "2021"

[dependencies]
comms = { path = "../comms" }
libmpv = { path = "../libmpv-rs" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
async-std = { version = "1.13", features = ["attributes", "std"] }

